name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.0.0'

      - name: Install dependencies
        run: yarn install

      - name: Add .env file
        run: |
          echo "AWS_ACCESS_KEY=\"$AWS_ACCESS_KEY\"" >> ./.env
          echo "AWS_SECRET_KEY=\"$AWS_SECRET_KEY\"" >> ./.env
          echo "AWS_REGION=\"$AWS_REGION\"" >> ./.env
          echo "TEST_BUCKET_NAME=\"$TEST_BUCKET_NAME\"" >> ./.env
          echo "TEST_DYNAMO_DB_NAME=\"$TEST_DYNAMO_DB_NAME\"" >> ./.env
        env:
          AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY}}
          AWS_SECRET_KEY: ${{secrets.AWS_SECRET_KEY}}
          AWS_REGION: ${{secrets.AWS_REGION}}
          TEST_BUCKET_NAME: ${{secrets.TEST_BUCKET_NAME}}
          TEST_DYNAMO_DB_NAME: ${{secrets.TEST_DYNAMO_DB_NAME}}

      - name: Test
        run: yarn test

  publish:
    permissions:
      id-token: "write"
      pages: "write"

    environment:
      name: "github-pages"
      url: "${{ steps.deployment.outputs.page_url }}"

    runs-on: ubuntu-latest
    needs: test
    # Make sure the branch reference is 'main' as you've specified 'main' above in the on.push.branches section
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.0.0'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: yarn install

      - name: Build documentation
        run: yarn build:doc

      - name: 'Upload Pages artifact'
        uses: 'actions/upload-pages-artifact@v2'
        with:
          path: 'docs/'

      - name: 'Deploy documentation to GitHub Pages'
        uses: 'actions/deploy-pages@v2'

      - name: Build
        run: yarn build

      - name: Publish to NPM
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

